
server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:49154/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: postgrespw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace